name: CI React + API

on:
  push:
  pull_request:

jobs:
  build-lint-test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        project:
          - CESIZENReact
          - CESIZENAPI

    defaults:
      run:
        working-directory: ${{ matrix.project }}

    steps:
      - name: Checkout React
        uses: actions/checkout@v6
        with:
          path: CESIZENReact

      - name: Clone API
        run: git clone https://x-access-token:${{ secrets.GH_PAT }}@github.com/Plabou102/CESIZENAPI.git CESIZENAPI

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: ${{ matrix.project }}/package-lock.json

      - run: npm ci
      - run: npm run build --if-present
      - run: npm run lint --if-present
      - run: npm test --if-present

  audit:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        project:
          - CESIZENReact
          - CESIZENAPI

    defaults:
      run:
        working-directory: ${{ matrix.project }}

    steps:
      - name: Checkout React
        uses: actions/checkout@v6
        with:
          path: CESIZENReact

      - name: Clone API
        run: git clone https://x-access-token:${{ secrets.GH_PAT }}@github.com/Plabou102/CESIZENAPI.git CESIZENAPI

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: ${{ matrix.project }}/package-lock.json

      - run: npm ci
      - run: npm audit --audit-level=high

  super-linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout React
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Super-Linter
        uses: super-linter/super-linter@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main