name: Notify Deploy

on:
  push:
    branches: [main, develop]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CESIZENdeploy
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GH_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/Plabou102/CESIZENdeploy/dispatches \
            -d '{"event_type":"api-updated","client_payload":{"message":"${{ github.event.head_commit.message }}","sha":"${{ github.sha }}","actor":"${{ github.actor }}"}}'